version: 0.2

env:
  variables:
    S3_BUCKET: "springboot-lambda-deep"
    ARTIFACT_NAME: "employee-app.zip"
    REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Maven pre-installed by CodeBuild..."
      - mvn -version

  build:
    commands:
      - echo "Building Spring Boot app with Maven..."
      - mvn clean package -DskipTests
      - echo "Creating ZIP package..."
      - zip -r $ARTIFACT_NAME target/*

  post_build:
    commands:
      - echo "Uploading ZIP to S3 bucket..."
      - aws s3 cp $ARTIFACT_NAME s3://$S3_BUCKET/$ARTIFACT_NAME
      - echo "Build and upload to S3 complete!"

artifacts:
  files:
    - $ARTIFACT_NAME
